services:
  - type: web
    name: tianshu
    runtime: python
    repo: https://github.com/shiyingzhang1990-del/tianshu
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:10000 --workers 1 --threads 4 --worker-class gthread --timeout 600 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEEPSEEK_API_KEY
        sync: false
